package com.example.web_browser

import android.annotation.SuppressLint
import android.os.Bundle
import android.text.SpannableStringBuilder
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.appcompat.widget.SearchView
import com.example.web_browser.MainActivity.Companion.tabsList
import com.example.web_browser.databinding.FragmentHomeBinding
import com.google.android.material.snackbar.Snackbar

class HomeFragment : Fragment() {
    // Declaration of the binding variable as a late-initialized property
    private lateinit var binding: FragmentHomeBinding

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        // Inflating the view from the XML file
        val view = inflater.inflate(R.layout.fragment_home, container, false)
        // Binding the variable 'binding' with the FragmentHomeBinding generated by Android
        binding = FragmentHomeBinding.bind(view)
        // Returning the view
        return view
    }

    override fun onResume() {
        super.onResume()

        // Get a reference to the MainActivity object
        val mainActivityRef = requireActivity() as MainActivity

        // Clear the text in searchViewHome and bottomSearchBar
        mainActivityRef.binding.bottomSearchBar.setText("")
        binding.searchViewHome.setQuery("", false)

        // Set web icon to search icon
        mainActivityRef.binding.webIcon.setImageResource(R.drawable.ic_search_white)

        // Set a listener for searchViewHome and check for internet connection,
        // change the tab based on the result
        binding.searchViewHome.setOnQueryTextListener(object :
            android.widget.SearchView.OnQueryTextListener {
            override fun onQueryTextSubmit(query: String?): Boolean {
                if (mainActivityRef.checkForInternetConnection(requireContext()))
                    mainActivityRef.changeTab(query!!, BrowseFragment(query))
                else
                    Snackbar.make(binding.root, "Check your connection", 3000).show()
                return true
            }

            override fun onQueryTextChange(newText: String?): Boolean = false
        })

        // Set a listener for the goButton in bottomSearchBar and check for internet connection,
        // change the tab based on the result
        mainActivityRef.binding.goButton.setOnClickListener {
            if (mainActivityRef.checkForInternetConnection(requireContext()))
                mainActivityRef.changeTab(
                    mainActivityRef.binding.bottomSearchBar.text.toString(),
                    BrowseFragment(mainActivityRef.binding.bottomSearchBar.text.toString())
                )
            else
                Snackbar.make(binding.root, "Check your connection", 3000).show()
        }
    }


}